### ISSUE TITLE
Gauge plugin causes IntelliJ to hang

### ISSUE THREAD

**Issue by akozlova** [getgauge/Intellij-Plugin#173]
Please see https://youtrack.jetbrains.com/issue/IDEA-157735 and duplicated issues for the additional info. The last issue I checked was about Gauge (0.2.0). 

P.S. We can black list this version of the plugin so people won't get bad experience before the fix appear.

**Comment by kashishm** [comment]
Thanks for logging the issue. We are working on it.

Following are the links to duplicate issues: 
* https://youtrack.jetbrains.com/issue/IDEA-158180
* https://youtrack.jetbrains.com/issue/IDEA-157853

**Comment by kashishm** [comment]
Ideally, the plugin should register to a specific module/project type(GaugeModuleType) so that for non-gauge projects, it should not get the control. Refer [this](https://intellij-support.jetbrains.com/hc/en-us/community/posts/207119229-Specify-module-type-in-plugin-xml-for-a-plugin) IntelliJ IDEA Open API and Plugin Development post for more details.

**Comment by kashishm** [comment]
We have released a [new version ](https://github.com/getgauge/Intellij-Plugin/releases/tag/v0.2.1) with the fix. let us know if the issue persists after updating.
