### ISSUE TITLE
Add a quick fix to convert parameter from Static to dynamic

### ISSUE THREAD

**Issue by zabil** [getgauge/Intellij-Plugin#260]
While authoring or reviewing existing steps suggest a [quick fix](https://www.jetbrains.com/help/idea/2017.1/applying-intention-actions.html) to convert a dynamic parameter to static and vice versa.

While the cursor is on a dynamic parameter.
![convert_to_dynamic_parameter](https://cloud.githubusercontent.com/assets/54427/26236022/cb255294-3c5d-11e7-9776-85d8769a8a91.png)

While the cursor is on a static parameter.

![convert_to_static_paramter](https://cloud.githubusercontent.com/assets/54427/26236185/8d6c86ce-3c5e-11e7-925e-fa695ea749e4.png)

**Comment by nehashri** [comment]
available in intellij nightly > 01-06-2017

**Comment by sguptatw** [comment]
Had couple of suggestions 
* instead of just changing from "" to <> and vice versa, Can we also give the user option to change the text in it. Like we do in autocomplete?
This will be helpful 'cause a dynamic parameter is not a proper noun or value
e.g: <number> to "1" and vice versa.
* After opting to change if user uses esc then the whole action is cancelled.
* After opting to change if the user uses enter then just change "" to <> and vice versa.
* This should not change/rename the parameter in the step annotation.

**Comment by nehashri** [comment]
- Selecting the parameter text after conversion.
- Working for concept files too now.

Fixes available in nightly > 14-06-2017

**Comment by sguptatw** [comment]
Not getting this option in IDE 

<img width="456" alt="screen shot 2017-06-16 at 11 00 21 am" src="https://user-images.githubusercontent.com/6310197/27213243-430cbb18-5283-11e7-9cce-ff5328c05c4f.png">

**Comment by sguptatw** [comment]
Converting "" to <> and the text change is one action. When I press `esc` the action should get cancelled. However this is retaining the text and changing only the placeholders.

**Comment by nehashri** [comment]
The action performed is converting the parameter type from static to dynamic or vice-versa. Only the text is selected after the action finishes for ease of changing the text if needed.
If we were to bring up a change text within action, it would be similar to refactoring/renaming the parameter. Since the action performed does not do renaming, escape does not cancel the action.
