### ISSUE TITLE
Intellij Runner should show the steps in at least the currently running scenario

### ISSUE THREAD

**Issue by Thunderforge** [getgauge/Intellij-Plugin#322]
Current Behavior
-----
When running a Gauge Spec via the Intellij Runner, no information is provided about the steps that are currently being run.

![image](https://user-images.githubusercontent.com/6200170/37475537-f27dd472-2840-11e8-895d-01fd93e337cb.png)

Requested Behavior
-----
At least for the currently running scenario, the steps should be visible.

![image](https://user-images.githubusercontent.com/6200170/37492501-a30e28ae-286f-11e8-95c0-d59f26d5610e.png)

If it is not possible to show future steps, then showing the currently running step, and any previous steps, is desired.

**Comment by zabil** [comment]
Gauge cannot run a specific step. 
The runner view summarizes all "runnable" nodes for e.g. the spec and the scenarios. We are note sure if we can get this working or if it's supported by IntelliJ.

I am closing this due to technical limitations. If you do find out a way to implement or do this please feel free to re-open.
