### ISSUE TITLE
Introduce local variable is slow

### ISSUE THREAD

**Issue by akozlova** [getgauge/Intellij-Plugin#51]
Please see https://youtrack.jetbrains.com/issue/IDEA-137884 for details.

**Comment by kashishm** [comment]
Released a new version which disables find usages feature temporarily.

**Comment by kashishm** [comment]
Fixed in [commit] (https://github.com/getgauge/Intellij-Plugin/commit/37e638fe596280fcaecf0ca0c4724198fe4c4ebe)
We have released [Intellij plugin(0.0.6)] (https://plugins.jetbrains.com/plugin/7535) and [github release (0.0.6)] (https://github.com/getgauge/Intellij-Plugin/releases) with the fix.
If the issue still persist, feel free to reopen this.
